### ISSUE TITLE
When Server goes down, restarts etc. the windows app crashes with no error

### ISSUE THREAD

**Issue by almostserious** [stijnvdb88/Snap.Net#10]
Whenever I restart or stop the server, the windows app just closes completely without any error message.
Needs to be manually restarted.

**Comment by stijnvdb88** [comment]
Thanks! Should be fixed in 0.20.0.2 release (https://github.com/stijnvdb88/Snap.Net/releases/tag/v0.20.02)

**Comment by almostserious** [comment]
I can confirm that it is fixed in 20.02. Thank you!
