### ISSUE TITLE
Snap.net connects to ControlServer but not StreamServerr?

### ISSUE THREAD

**Issue by morithil** [stijnvdb88/Snap.Net#18]
Hi there,

My setup was previously working fine (RPI running Snapserver, Windows Snap.Net client with default settings, various other RPI clients around the house) until yesterday.

Snap.net connects on my PC and shows other connected clients, but no longer lists the Snap.net client PC and does not play music from Snapserver.

My RPI snapserver service reports 'ControlServer: New connection: [windows pc IP]' but there is no record of the StreamServer connecting or a 'hello' from the PC.

**Comment by stijnvdb88** [comment]
Hi, 

the control server is connected to on startup, but streaming is initialized per sound card. Have you checked the Player window to make sure the audio device is playing? Clicking the play button there forces it to start - if that doesn't work you should be seeing some kind of error notification at least. If that's also not happening, please take a look at the Settings for the notification settings in case they're off.

**Comment by morithil** [comment]
Thanks @stijnvdb88 , pressing 'Play' on the Audio source was all I needed! Wasn't getting any error notifications or indication that I didn't have any source active so it was a bit hidden, but I got there in the end, woops!
