### ISSUE TITLE
latest commandline version

### ISSUE THREAD

**Issue by DEvmIb** [stijnvdb88/Snap.Net#2]
please put the latest version of the commandline version on the release page, i have 0.19.0-2. many thx :)

**Comment by stijnvdb88** [comment]
Hi! if you're talking about snapclient, that's outside of the scope of this repo - badaix will be releasing those on the main snapcast releases page :) That said, this project does come with the latest version of snapclient bundled in: https://github.com/stijnvdb88/Snap.Net/tree/master/SnapClient - this was built from snapcast's master branch (#adfed6a)
