### ISSUE TITLE
iOS: support dark mode

### ISSUE THREAD

**Issue by stijnvdb88** [stijnvdb88/Snap.Net#22]
Per AppStore user review:
> Settings area currently doesn’t bother with labels to tell you what the 3 fields are for, other than pre-populating two port values. UPDATE: I was confused by the settings because this app does not support dark mode. The gear icon is also hidden in dark mode which was rather confusing at first.

**Comment by giantorth** [comment]
Thanks a ton for fixing this!

**Comment by stijnvdb88** [comment]
No problem!
