### ISSUE TITLE
Snap.net not runing with lates windows 10 version

### ISSUE THREAD

**Issue by zsamiatt** [stijnvdb88/Snap.Net#30]
Hello,
I have win 10 19043.1081  [https://support.microsoft.com/en-us/topic/june-21-2021-kb5003690-os-builds-19041-1081-19042-1081-and-19043-1081-preview-11a7581f-2a01-47d5-ba12-431709ee2248](url)

After the win 10 has been updated snap.net 0.24 and 0.25 can not runing.

The name of the module that caused the error is: kernelbase.dll
process has been atymed due to an unhandled exception
Source: .net runtime
identifier: 1026

**Comment by stijnvdb88** [comment]
Hi! I updated to that version of Windows today, but still can't reproduce the crash. Does it happen on startup?

**Comment by zsamiatt** [comment]
> 
> 
> Hi! I updated to that version of Windows today, but still can't reproduce the crash. Does it happen on startup?

Hello, 
I try Startup and manual start but the program can not runing after win update.

**Comment by zsamiatt** [comment]
I try 0.23 version. It is working good. 0.24,025 can not run.

**Comment by stijnvdb88** [comment]
Hi, I still haven't been able to reproduce this so I will need your help to fix it. Could you please follow these steps?
* Open Event Viewer
* On the left side, Open "Windows Logs", then select "Application"
* Start Snap.Net (0.25) and wait for it to crash
* In the Event Viewer window, hit refresh (F5)
* If there is a new ".NET Runtime" entry with an error, please send me everything inside of the "General" tab
It should look something like this:

![image](https://user-images.githubusercontent.com/4498834/125052211-a05e0100-e09b-11eb-8670-a6553df72f06.png)

(this screenshot is from an intentional crash, yours should look a bit different)

Thanks!

**Comment by zsamiatt** [comment]
Alkalmazás: Snap.Net.exe
Keretrendszer verziószáma: v4.0.30319
Leírás: A folyamat egy nem kezelt kivétel miatt meg lett szakítva.
Kivétel adatai: System.Xml.XmlException
   a következő helyen: System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   a következő helyen: System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   a következő helyen: System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   a következő helyen: System.Xml.XmlTextReaderImpl.ParseText()
   a következő helyen: System.Xml.XmlTextReaderImpl.ParseElementContent()
   a következő helyen: System.Xml.XmlTextReaderImpl.Read()
   a következő helyen: System.Xml.XmlTextReader.Read()
   a következő helyen: System.Xml.XmlTextReaderImpl.Skip()
   a következő helyen: System.Xml.XmlTextReader.Skip()
   a következő helyen: System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   a következő helyen: System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   a következő helyen: System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   a következő helyen: System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   a következő helyen: System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Kivétel adatai: System.Configuration.ConfigurationErrorsException
   a következő helyen: System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   a következő helyen: System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   a következő helyen: System.Configuration.Configuration..ctor(System.String, System.Type, System.Object[])
   a következő helyen: System.Configuration.ClientConfigurationHost.OpenExeConfiguration(System.Configuration.ConfigurationFileMap, Boolean, System.Configuration.ConfigurationUserLevel, System.String)
   a következő helyen: System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(System.Configuration.ConfigurationFileMap, Boolean, System.Configuration.ConfigurationUserLevel, System.String, Boolean)
   a következő helyen: System.Configuration.ClientSettingsStore.ReadSettingsFromFile(System.String, System.String, Boolean)
   a következő helyen: System.Configuration.LocalFileSettingsProvider.GetSettingValuesFromFile(System.String, System.String, Boolean, System.Configuration.SettingsPropertyCollection)
   a következő helyen: System.Configuration.LocalFileSettingsProvider.Upgrade(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection, Boolean)
   a következő helyen: System.Configuration.LocalFileSettingsProvider.Upgrade(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   a következő helyen: System.Configuration.ApplicationSettingsBase.Upgrade()
   a következő helyen: SnapDotNet.SnapSettings.Init()
   a következő helyen: SnapDotNet.Snapcast.OnStartup(System.Windows.StartupEventArgs)
   a következő helyen: System.Windows.Application.<.ctor>b__1_0(System.Object)
   a következő helyen: System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   a következő helyen: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   a következő helyen: System.Windows.Threading.DispatcherOperation.InvokeImpl()
   a következő helyen: System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   a következő helyen: MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   a következő helyen: System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   a következő helyen: System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   a következő helyen: System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   a következő helyen: MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   a következő helyen: System.Windows.Threading.DispatcherOperation.Invoke()
   a következő helyen: System.Windows.Threading.Dispatcher.ProcessQueue()
   a következő helyen: System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   a következő helyen: MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   a következő helyen: MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   a következő helyen: System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   a következő helyen: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   a következő helyen: System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   a következő helyen: MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   a következő helyen: MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   a következő helyen: System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   a következő helyen: System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   a következő helyen: System.Windows.Application.RunDispatcher(System.Object)
   a következő helyen: System.Windows.Application.RunInternal(System.Windows.Window)
   a következő helyen: System.Windows.Application.Run(System.Windows.Window)
   a következő helyen: SnapDotNet.SingleInstanceManager.OnStartup(Microsoft.VisualBasic.ApplicationServices.StartupEventArgs)
   a következő helyen: Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   a következő helyen: Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(System.String[])
   a következő helyen: SnapDotNet.EntryPoint.Main(System.String[])

**Comment by stijnvdb88** [comment]
Thanks! I think we're getting close - this looks like it's caused by a parse error while trying to read your user config file, but I'm not sure how a Windows update could've caused that.

Can you please try this:

* Go to C:\Users\<yourname>\AppData\Local\SnapDotNet\Snap.Net.exe_Url_<somerandomgibberishhere>\0.25.0.0, and send me the contents of the user.config file
* Rename that file/move it somewehere else
* Start Snap.Net

If it still crashes after that, you can also try renaming the SnapDotNet folder (2 directories up).

**Comment by zsamiatt** [comment]
Hello, Working. I resolve the problem. Delete appdata\..\Snapdonet folder and reinstall 0.25. Everything working good. Thx your help
