### ISSUE TITLE
Keine Ton (Snap.Net.Broadcast)

### ISSUE THREAD

**Issue by Synec5** [stijnvdb88/Snap.Net#32]
Hallo,

ich höre kein Ton wenn ich Broadcast verwende. Eine Verbindung zum Server wird aufgebaut.

Ich verwende Virtual Audio Cable. Ton Ausgabe ist darauf eingestellt.

eintrag in der " /etc/snapserver.conf":

stream = spotify:///librespot?name=Spotify&devicename=Snapcast (Muliroom)&killall=true
stream = tcp://0.0.0.0?port=4953&name=snapbroadcast&mode=server

**Comment by stijnvdb88** [comment]
Hi! Are the broadcast settings in Snap.Net configured correctly? It should look like this - with the broadcast button on the right enabled:

![image](https://user-images.githubusercontent.com/4498834/138242828-a60cc9c3-f2ef-47a6-90e5-c78ac833379c.png)
Also, while music is playing on the Virtual Audio Cable device, does the Snap.Net icon in the tray show a red circle like this?
![image](https://user-images.githubusercontent.com/4498834/138243195-aadd5c98-3601-41df-ae6b-da3736f388ca.png)

Finally, the group that contains your speakers should be set to the broadcast stream:
![image](https://user-images.githubusercontent.com/4498834/138243435-a694977e-2a57-46ae-8383-6bc146ca1ede.png)

You can also try starting the stream directly via the command line app, in case it's failing silently somehow:
Open a command prompt in  `C:\Program Files\Snap.Net`, and run:

```Snap.Net.Broadcast.exe --list``` 
that should give you the list of speakers - use the number next to your Virtual Audio Cable device for the next step (in this example it's "4"):

```Snap.Net.Broadcast.exe -h <server-ip> -s 4``` 

Also try restarting snapserver and Snap.Net - I've seen issues with putting the computer to sleep while broadcasting, which required restarting both to fix.

Good luck!

**Comment by YeonV** [comment]
having similar issues:
![image](https://user-images.githubusercontent.com/28861537/140003399-813b829b-e03f-49b1-bd74-5cbc9fc4ddeb.png)
the stream says idle :(

any help would be awesome <3
