### ISSUE TITLE
Snap.Net >v0.26.0.1 crashes when opening volume mixer

### ISSUE THREAD

**Issue by throny** [stijnvdb88/Snap.Net#36]
I just updated my 0.25 to the latest release. However when opening the volume mixer for the different clients in v0.26.0.1/2 the application crashes without further information. The issue does not occur in v0.26.0.0 
I can reproduce it on different windows clients. 
I guess it's something with the Metadata API.

We're running the docker image mazzolino/librespot-snapserver if that might be a reason but I couldn't find any errors in the logfile.

I can provide you with logs if you want :) (and if you tell me where I could find them)

**Comment by stijnvdb88** [comment]
Hi! I am having trouble reproducing this, so logs would definitely help :) You can follow [these instructions](https://github.com/stijnvdb88/Snap.Net/issues/30#issuecomment-877030679) to get them.

Thanks!

**Comment by throny** [comment]
Hi,
I almost thought so, that's why I brought up the Docker image.

This is the error log:
`Anwendung: Snap.Net.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.NullReferenceException
   bei SnapDotNet.SnapControl.Group.<_OnStreamPropertiesUpdated>b__9_0()
   bei System.Windows.Threading.Dispatcher.Invoke(System.Action, System.Windows.Threading.DispatcherPriority, System.Threading.CancellationToken, System.TimeSpan)
   bei System.Windows.Threading.Dispatcher.Invoke(System.Action)
   bei SnapDotNet.SnapControl.Group._OnStreamPropertiesUpdated()
   bei SnapDotNet.SnapControl.Group._OnGroupUpdated()
   bei SnapDotNet.SnapControl.Group..ctor(SnapDotNet.ControlClient.SnapcastClient, SnapDotNet.ControlClient.JsonRpcData.Group)
   bei SnapDotNet.SnapControl.SnapControl._OnServerUpdated()
   bei SnapDotNet.SnapControl.SnapControl..ctor(Hardcodet.Wpf.TaskbarNotification.Interop.Point, SnapDotNet.ControlClient.SnapcastClient)
   bei SnapDotNet.Snapcast.ShowSnapPane(Boolean)
   bei SnapDotNet.NotifyIconViewModel+<>c.<get_ShowBalloonCommand>b__9_1()
   bei SnapDotNet.DelegateCommand.Execute(System.Object)
   bei Hardcodet.Wpf.TaskbarNotification.Util.ExecuteIfEnabled(System.Windows.Input.ICommand, System.Object, System.Windows.IInputElement)
   bei Hardcodet.Wpf.TaskbarNotification.TaskbarIcon+<>c__DisplayClasse.<OnMouseEvent>b__8()
   bei System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   bei System.Windows.Threading.DispatcherOperation.Wait(System.TimeSpan)
   bei System.Windows.Threading.Dispatcher.InvokeImpl(System.Windows.Threading.DispatcherOperation, System.Threading.CancellationToken, System.TimeSpan)
   bei System.Windows.Threading.Dispatcher.Invoke(System.Action, System.Windows.Threading.DispatcherPriority, System.Threading.CancellationToken, System.TimeSpan)
   bei System.Windows.Threading.Dispatcher.Invoke(System.Action)
   bei Hardcodet.Wpf.TaskbarNotification.TaskbarIcon.DoSingleClickAction(System.Object)
   bei System.Threading.TimerQueueTimer.CallCallbackInContext(System.Object)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.TimerQueueTimer.CallCallback()
   bei System.Threading.TimerQueueTimer.Fire()
   bei System.Threading.TimerQueue.FireNextTimers()
   bei System.Threading.TimerQueue.AppDomainTimerCallback(Int32)
`

**Comment by stijnvdb88** [comment]
thanks for that! fixed for next release
