### ISSUE TITLE
Click Snap.Net icon in tray and app exits/crashes/closes out

### ISSUE THREAD

**Issue by cruiser-rtd** [stijnvdb88/Snap.Net#39]
Had prior version Snap.Net-0.25.0.0 installed.
Updated to Snap.Net-0.26.0.2 and app will run and play the last stream source 0.25 was playing from.
If I click the Snap.Net tray icon, instead of opening the control surface, the app crashes/closes out and stops playback.

Can relaunch app, tray icon reappears, and playback resumes.

Settings, Player and Broadcast screens all open fine.

Uninstalled Snap.Net - manually deleted \Program Files\Snap.Net folder as it was left behind, rebooted, installed 0.26.02, problem is still there.

**Comment by cruiser-rtd** [comment]
In case it matters, playback source is Raspberry Pi with Mopidy installed and Iris interface.
Raspbian GNU/Linux 10 (buster)
Mopidy 3.1.1
Isis 3.62.0

**Comment by stijnvdb88** [comment]
Hi! which version of snapserver are you running? This sounds like it could be the same issue as https://github.com/stijnvdb88/Snap.Net/issues/36, which has been fixed but hasn't made it into a release yet

**Comment by cruiser-rtd** [comment]
Hi, thanks for asking about the snapserver version.  I'd mistakenly assumed it was being updated by all of the other updates.  I found it to be version 0.24.0 upgraded it to 0.26.0 solved the problem with Snap.Net.
