### ISSUE TITLE
How do you install the client?

### ISSUE THREAD

**Issue by kriegfalke** [stijnvdb88/Snap.Net#4]
Hello,
I am trying to compile the file to get Snapserver running. I can see there is an .EXE file and no installer. There is no guide to install either. Can you tell me how to run it?

**Comment by kriegfalke** [comment]
I got my answer! It's in the "Release" section. Sorry, I'm new to this :)

**Comment by stijnvdb88** [comment]
No problem - glad you figured it out! I'll add a link to it on the main page as well :)
