### ISSUE TITLE
[Request][Mobile iOS] Support opus codec

### ISSUE THREAD

**Issue by guerman5** [stijnvdb88/Snap.Net#44]
Hi Stijn Van der Borght

Thanks for your efforts. I've been using this iOS client for a while now, very useful and stable.

Using the default codec for a couple players on wifi has worked well.
But on a new scenario, I need to increase players and keep low traffic, at expense of bitrate, so tried to use codec=opus on snapserver. It only worked in android clients not in ios.

Then I found the release notes and confirmed why
_1.1 Mar 14, 2021
Added playback support! Your iOS device can now act as a snapclient, for now only the default (flac) codec is supported._

May I ask if possible to add support for opus decoding on the iOS client.

Double thanks

Guerman

**Comment by stijnvdb88** [comment]
Hi!

I just released an update of the iOS app on the AppStore (0.26.0), which adds support for opus.

**Comment by guerman5** [comment]
Hi Stijn!!

I found out about 0.26.0 just yesterday (before reading your message), thank you very much!

I've been testing it using opus _max_ and _auto_ bitrates. For reference:
ios 15.6.1/15.7 (6s); 14.8.1/15.7/16.0.2 (12)

Snapcast client is FLYING! consumes around 60~70Kbps (on opus max), flac was taking double bandwidth. Although I plan to use it mostly on opus _auto_ mode, on a vpn ;) . 

Opus support is such great addition. Thanks a lot again



_ps: now i can convince more friends to get the app ;)_
