### ISSUE TITLE
Android APK available for download?

### ISSUE THREAD

**Issue by almostserious** [stijnvdb88/Snap.Net#7]
Hi, it looks like there is also an IOS and Android app available.
Is this already precompiled to download somewhere?
In the releases i can only find the windows exe

**Comment by stijnvdb88** [comment]
Hi! I've published the apk in releases now: https://github.com/stijnvdb88/Snap.Net/releases/download/v0.20.0.0/Snap.Net-0.20.0.apk

Honestly it's mostly just a .NET port of https://github.com/badaix/snapdroid, which is also the reason I didn't add it to the releases initially. At the moment it does not offer advantages/improvements over snapdroid. 

The iOS version is trickier unfortunately - it can only be distributed via the App Store. That requires a developer account, which means paying Apple 99$ per year. badaix suggested making it a paid app to recover the cost, but that implies a lot of financial setup I'm not ready to dive into right now :) The goal is still to get the iOS version published somehow, preferably free of charge.

**Comment by almostserious** [comment]
Thank you :) Actually it has one benefit to the snapdroid. It doesnt turn off playback when I'm unplugging the 3.5mm or switch the connected HDMI device off.  (Have to test some more to be 100% sure). badaix seems to have found the issue already, but its not yet implemented. And my knowledge is not enough to make a PR. But initial testing your app keeps connected and working :)

**Comment by almostserious** [comment]
Yes indeed, i installed it now on 3 of the devices i had troubles with and it works very well :) 
I found 2 more issues, for which  I opened new issues. 
Can I also ask you if your planning to add an autostart to your app?

**Comment by stijnvdb88** [comment]
Haha you managed to pick out exactly the one thing I added which snapdroid does not have! :) There's a bunch of other features snapdroid does which are missing here, auto-detecting snapserver is one of them. I honestly simply forgot about the autostart - will add it to the todo list. Thanks for all the feedback!

**Comment by Drizzt321** [comment]
So I'm just finding this project, and only recently started using Snapcast/Mopidy, and I'm looking for something more efficient than AirMusic to stream from my Android to Snapserver via Shairport-Sync. The way I'm reading it, this project's Android is more controller, rather than audio source, correct? Anyone know of a better audio source from Android -> Snapserver?

**Comment by stijnvdb88** [comment]
Hi! Yes: since Android 10 it should be possible to capture system audio (https://developer.android.com/guide/topics/media/av-capture). The big question is whether Xamarin has exposed all of these API's. I'll spend some time playing around with this, it would be neat feature to have.

**Comment by Chaphasilor** [comment]
That would be amazing! If you need any help with this, just let me know. I haven't used Xamarin yet, but maybe I could help test/debug things :)

**Comment by stijnvdb88** [comment]
Hi! there's been some progress on this, but let's move the broadcast discussion over to #33 for clarity's sake. I'll close this issue since most people will have figured out by now that there is indeed an APK available for download :)
