### ISSUE TITLE
Android App - IP Address with trailing space cannot be read

### ISSUE THREAD

**Issue by almostserious** [stijnvdb88/Snap.Net#8]
When the IP Address has a trailing space (something that easily happens when using the keyboards recommendations) the app does not connect.

**Comment by stijnvdb88** [comment]
This issue should be fixed in the new pre-release: https://github.com/stijnvdb88/Snap.Net/releases/tag/v0.20.01 :)

**Comment by almostserious** [comment]
works great 👍  I'll close it
